### ISSUE TITLE
Output file not updated?

### ISSUE THREAD

**Issue by krassdanke** [marcselman/react-l20n#2]
Hi, this is concerning my preceeding pull request #1.

You have updated the project and I can confirm it is working for me. But since then, I always have to manually rebuild the react-l20n-u module because the output file (./build/react-l20n.js) is not updated correctly. You can spot the differences at line 73 (old output) // line 71 (new output) and following.

Please rebuild and publish again so that my ci processes do not have to come up with a workaround anymore.

Thanks in advance; also for your efforts concerning my previous issue.

**Comment by marcselman** [comment]
Hi Daniel,

What version are you using?
The latest version is 0.0.14.

See: https://github.com/marcselman/react-l20n/blob/master/build/react-l20n.js#L73

**Comment by krassdanke** [comment]
I am using the latest version 0.0.14.
I double-checked the build output provided with each release (0.0.14, 0.0.13). They are definitely two different outputs.

But how can it be that there is the same error that you just fixed in the output build of version 0.0.14? When I rebuild it, I get another different output that works. It does not contain the same problem.

**Comment by marcselman** [comment]
I suppose this problem is no longer there in the latest builds?

**Comment by krassdanke** [comment]
Sorry that I did not give further feedback.
Problem seems to be solved but had been worked around since then. Still I do not know the cause of the problem... Thanks for your support anyways!
